# Generated by Django 4.1 on 2022-09-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_review_mytasks_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytasks',
            old_name='is_done',
            new_name='is_finished',
        ),
    ]
