# Generated by Django 4.1 on 2022-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_mytasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytasks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
