# Generated by Django 4.1 on 2022-09-29 02:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0005_alter_mytasks_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTasks',
            new_name='Task',
        ),
    ]
